### ISSUE TITLE
Example for MPI/distributed training?

### ISSUE THREAD

**Issue by okhat** [NervanaSystems/ngraph#1033]
Are there any examples/docs for distributed training (e.g., via MPI) with ngraph?

**Comment by wenzhe-nrv** [comment]
There is a distributed test with `Allreduce` op implemented via MPI.
https://github.com/NervanaSystems/ngraph/blob/master/test/distributed.cpp

We are working on framework integration of distributed training with nGraph. For example, multi-node TensorFlow training with Horovod adds an allreduce op in TF graph, which needs to be supported in nGraph. Other needed collective communication ops will be added for model parallel training in future.

**Comment by diyessi** [comment]
Merged to master now, doc in the next export (in progress).
