### ISSUE TITLE
[Question] - Reshape implimentation

### ISSUE THREAD

**Issue by 0shimax** [NervanaSystems/ngraph#11]
I got error(`NotImplementedError("Reshape can only support flatten"`) in `importer.import_graph_def(tf.get_default_graph().as_graph_def())` when I used tf.reshape in my tenforslow model.
I also got same error when used `tf.contrib.layers.flatten()`.
Can't we input 4d array into `tf.reshape` or `tf.contrib.layers.flatten()` in ngraph Reshape implimentation?

**Comment by jknight-nervana** [comment]
Hi @0shimax. Sorry about that sharp corner you hit. We are actually moving away from/deprecating the TF importer that you are using and towards an XLA backend approach as described [here](https://www.intelnervana.com/intel-nervana-graph-and-neon-3-0-updates/). Keep an eye on our repo https://github.com/NervanaSystems/ngraph-tensorflow once we open this up to the public.

**Comment by 0shimax** [comment]
@jknight-nervana 
Thank you for the reply. I got it. I wait that you develop TF importer on XLA.
BTW, I can't open https://github.com/NervanaSystems/ngraph-tensorflow. Is this private repository?

**Comment by jknight-nervana** [comment]
Correct, Github 404's on private repo links if you're not part of the project.

**Comment by 0shimax** [comment]
I got it. Thank you for the information.
