### ISSUE TITLE
Missing import in algebraic_simplification.cpp

### ISSUE THREAD

**Issue by anmolsahoo25** [NervanaSystems/ngraph#1100]
In the file, 
https://github.com/NervanaSystems/ngraph/blob/master/src/ngraph/pass/algebraic_simplification.cpp

The import for the library ``<numeric>`` is missing. The compilation fails with the error that ``iota`` is not part of ``std``.

Can I submit a pull request for this, in case this bug is valid.

**Comment by diyessi** [comment]
Thanks. This is already fixed in another PR. There are a few headers that are automatically included on some platforms but not others, and this is one of them.

**Comment by anmolsahoo25** [comment]
Hi. 

Thanks for you reply. In the PR #770, this include is added to the tensor_mask.cpp file. 

Here the issue is in the algebraic_simplification.cpp file. Does this need to be fixed?

**Comment by rkimballn1** [comment]
This issue was resolved as part of PR #1101
