### ISSUE TITLE
Compilation failure in gpu_emitter.cpp

### ISSUE THREAD

**Issue by WilliamTambellini** [NervanaSystems/ngraph#1136]
Hi everybody,
I know the ngraph doc mentions gcc 4 but just to report a compilation failure with ngraph master 
commit 9be92aaeea01685c7352c162fbc6fc3778e0bd1e
in gpu_emitter using gcc 5.3 on CentOS 7 :  

[ 74%] Building CXX object src/ngraph/runtime/gpu/CMakeFiles/gpu_backend.dir/gpu_emitter.cpp.o
cd /home/wtambellini/repos/ngraph/build/src/ngraph/runtime/gpu && gcc-5.3.0/bin/g++  -Dgpu_backend_EXPORTS -I/home/wtambellini/repos/ngraph/src/ngraph -I/home/wtambellini/repos/ngraph/src -isystem /usr/local/cuda/include -isystem /home/wtambellini/repos/ngraph/build/json/src/ext_json/include -isystem /home/wtambellini/repos/ngraph/build -isystem /home/wtambellini/repos/ngraph/build/mkldnn/include -isystem /home/wtambellini/repos/ngraph/build/eigen/src  -DEIGEN_MPL2_ONLY -std=c++11 -march=native -O2 -fPIE -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -fstack-protector-strong -DNGRAPH_CPU_ENABLE -DIN_NGRAPH_LIBRARY -fPIC   -o CMakeFiles/gpu_backend.dir/gpu_emitter.cpp.o -c /home/wtambellini/repos/ngraph/src/ngraph/runtime/gpu/gpu_emitter.cpp
In file included from gcc-5.3.0/include/c++/5.3.0/string:52:0,
                 from gcc-5.3.0/include/c++/5.3.0/random:40,
                 from gcc-5.3.0/include/c++/5.3.0/bits/stl_algo.h:66,
                 from gcc-5.3.0/include/c++/5.3.0/algorithm:62,
                 from /home/wtambellini/repos/ngraph/src/ngraph/runtime/gpu/gpu_emitter.cpp:17:
gcc-5.3.0/include/c++/5.3.0/bits/basic_string.h: In instantiation of ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = std::basic_string<char>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’:
gcc-5.3.0/include/c++/5.3.0/bits/basic_string.h:4164:27:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = std::basic_string<char>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
gcc-5.3.0/include/c++/5.3.0/bits/basic_string.tcc:673:31:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(_InputIterator, _InputIterator, const _Alloc&) [with _InputIterator = std::basic_string<char>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
/home/wtambellini/repos/ngraph/src/ngraph/runtime/gpu/gpu_emitter.cpp:2234:60:   required from here
gcc-5.3.0/include/c++/5.3.0/bits/basic_string.h:4142:76: error: no type named ‘iterator_category’ in ‘struct std::iterator_traits<std::basic_string<char> >’
           typedef typename iterator_traits<_InIterator>::iterator_category _Tag;

Here is gpu_emitter.cpp line 2234 : 

// exponentiate with fused sum reduction to calculate softmax denominator
size_t exp_sum_reduce =
         cuda_emitter
                               	->build_elementwise_collective<ngraph::op::Exp, ngraph::op::Add>(
                                    external_function->ctx().get(),
                                    {{args[0].get_type(), out[0].get_type()}},
                                    args[0].get_shape(),
                                    {},
                                    axes,
                                    true /* multi-output */);

Kind

**Comment by WilliamTambellini** [comment]
Hum, gcc 5.1 is hitting some warnings in mkldnn : 

[  4%] Building CXX object src/CMakeFiles/mkldnn.dir/common/memory.cpp.o
/home/wtambellini/repos/ngraph/build/mkldnn/src/src/common/memory.cpp: In function ‘mkldnn::impl::status_t mkldnn_sum_primitive_desc_create_v2(mkldnn::impl::primitive_desc_t**, const memory_desc_t*, int, const float*, const primitive_desc_t**, const primitive_attr_t*)’:
/home/wtambellini/repos/ngraph/build/mkldnn/src/src/common/memory.cpp:329:42: error: array subscript is above array bounds [-Werror=array-bounds]
             if (i_mpds[i]->desc()->dims[d] != dims[d])
                                          ^

 
but gcc 4.8 indeed succeeds.
I guess this ticket could be closed.

**Comment by WilliamTambellini** [comment]
Found the issue : gcc 4.8 does nt correctly understand/construct the inline dtypes vector of strings : 
{{args[0].get_type(), out[0].get_type()}}

Doing a manual creation/init seems to pass : 
std::vector<std::string> dtypes(2);
dtypes[0] = args[0].get_type();
dtypes[1] = out[0].get_type();
size_t exp_sum_reduce = cuda_emitter->build_elementwise_collective<ngraph::op::Exp, ngraph::op::Add>( dtypes, ... )
but there is perhaps better avoiding copy.

I still don't understand how could ngraph compile on your CI/jenkins jobs.
@csullivan  Do you have a CI job continuously building ngraph under CentOS7 / gcc 4.8.2 with cuda backend on ?

Kind

**Comment by csullivan** [comment]
Thanks for pointing this out @WilliamTambellini. It has been addressed in #1561. Closing this, but do follow up if you have further issues.
