### ISSUE TITLE
C API support

### ISSUE THREAD

**Issue by QuPengfei** [NervanaSystems/ngraph#1187]
Is there a plan to define the C API?

**Comment by diyessi** [comment]
Eventually, when something needs it. It would just wrap the C++, so we want to wait for that to settle first.

**Comment by QuPengfei** [comment]
FFmpeg need the C API. If C API wrapper is ready, it will be easy to enable nGraph in the FFmpeg.

**Comment by diyessi** [comment]
How are you trying to use nGraph in FFmpeg?.

**Comment by QuPengfei** [comment]
The use case is simple. it focus on the inference. During the media decoding or transcoding, the end user can do the inference with  the nGraph as one of the backend. it helps accelerate on the different HW.

**Comment by diyessi** [comment]
In your use case, I think you would have a specific graph in mind, and what you really want is the ability to produce a small library with a C API that runs that graph.
