### ISSUE TITLE
Using Ngraph with Anaconda

### ISSUE THREAD

**Issue by dmenescal** [NervanaSystems/ngraph#12]
Good evening,

I would like to use the following configs:
Nervana Ngraph + Intel Python Distribution via Anaconda

However, according to installation procedure, i need to use virtualenv (from neon) in order to install ngraph. When neon build a venv, it points to a python bin different from my desire.

Could you help me to make neon create a virtualenv with Intel python, in order to install ngraph above this?

Thanks!

**Comment by tyler-nervana** [comment]
Hi, you know longer need to install within the neon virtualenv - ngraph is now completely standalone. You can install within your custom environment using `pip install -e .` from within the ngraph directory.

**Comment by dmenescal** [comment]
Thanks Tyler! It worked!!!
