### ISSUE TITLE
[Question] - np.sign name "out" is not defined

### ISSUE THREAD

**Issue by pedronahum** [NervanaSystems/ngraph#14]
Hi,

I am trying to implement a function that calls the sign(x) function on a tensor, and I get the error that the name out is not defined. How can I define such out_axes?

The function sign(x) in op_graph.py is calling the class SignOp, this UnaryELementWiseOp class, however, doesnt have the generate_adjoints function implemented. Could this be related?

Thanks,

Pedro N.

**Comment by diyessi** [comment]
In cputransform.py for sign it should say out={}. This will be fixed in the next update.

generate_adjoints is for autodiff; sign doesn't have a derivative so it has no generate_adjoints.

**Comment by pedronahum** [comment]
Perfect! Thank you
