### ISSUE TITLE
c++ internal compiler error

### ISSUE THREAD

**Issue by SynchronicitydotAI** [NervanaSystems/ngraph#1673]
After a fresh pull today I am getting the following error when attempting to build the docker container on a new CentOS 7.4 install:

$ make check_gcc OS=centos74

...

cd /home/dockuser/ngraph-test/BUILD-GCC/src/ngraph/runtime/cpu && /usr/bin/c++  -DEIGEN_OPENMP -DNGRAPH_VERSION=\"0.8.0-rc.0+f16ace9\" -Dcpu_backend_EXPORTS -I/home/dockuser/ngraph-test/src/ngraph -I/home/dockuser/ngraph-test/src -isystem /home/dockuser/ngraph-test/src/ngraph/runtime/cpu/libmkldnn -isystem /home/dockuser/ngraph-test/BUILD-GCC/json/src/ext_json/include -isystem /home/dockuser/ngraph-test/BUILD-GCC/mkldnn/include -isystem /home/dockuser/ngraph-test/BUILD-GCC/eigen/src -isystem /home/dockuser/ngraph-test/BUILD-GCC/tbb/tbb-src/include -isystem /home/dockuser/ngraph-test/BUILD-GCC  -DEIGEN_MPL2_ONLY -std=c++11 -march=native -O2 -fPIE -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -fstack-protector -DNGRAPH_CPU_ENABLE -DIN_NGRAPH_LIBRARY -DGRAPHVIZ_FOUND -g -fPIC   -fopenmp -o CMakeFiles/cpu_backend.dir/cpu_kernel_utils.cpp.o -c /home/dockuser/ngraph-test/src/ngraph/runtime/cpu/cpu_kernel_utils.cpp
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [src/ngraph/runtime/cpu/CMakeFiles/cpu_backend.dir/builder/dot.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/dockuser/ngraph-test/BUILD-GCC'
make[1]: *** [src/ngraph/runtime/cpu/CMakeFiles/cpu_backend.dir/all] Error 2
make[1]: Leaving directory `/home/dockuser/ngraph-test/BUILD-GCC'
make: *** [all] Error 2
make: *** [build_gcc] Error 2

**Comment by SynchronicitydotAI** [comment]
Am I somehow inadvertently checking out a development branch with all of this? I've followed the instructions exactly for both the Docker and compiler build and install, both have been failing for over a month now.

We are evaluating ngraph for production ML model deployment; I can't imagine that this compiler is being used in other production environments if even the compiler build itself is broken and has been broken for at least several weeks now.

**Comment by rkimballn1** [comment]
We do run tests for every commit to master and the build is passing on our internal CI machines running Ubuntu 16.40, Ubuntu 18.84, and CentOS 7.4 in docker and in Travis with Ubuntu 16.04 and CentOS 7 in docker. Master is currently passing all of our tests.
All of the docker files are in the repo so you can look at those to see if there are any problems.
Unfortunately I do not use docker for development, favoring building on my dev machine, so I can't address your docker issues. Can you try a non-docker build?

**Comment by diyessi** [comment]
"Internal compiler error" means just what it says -- gcc crashed; it's a bug in the version of gcc you are using. There are some files in nGraph that need a lot of memory to compile; this could be gcc's way of telling you that it ran out of memory. That would be my first guess.
Verson 1.0 will be the first production release. We're not there yet.

**Comment by SynchronicitydotAI** [comment]
Are there any suggestions / hardware compatibility guides for the build platform on this? This is a 16GB quad core 3.2GHz host with a reasonably fast SSD..?

**Comment by rkimballn1** [comment]
I asked around. Try removing the `-j` option for make.

**Comment by diyessi** [comment]
16G is what most people here use (Ubuntu), but not with -j, as @rkimballn1 notes. For some of the files, the compile process gets into the teen gigs of memory.

**Comment by aprocter** [comment]
Dialing it back to (say) -j4 or -j2 might work too—whatever value happens to be small enough to keep you from running out of RAM.

**Comment by rkimballn1** [comment]
Or better yet, just remove the -j option. I would rather see it work then have yet another faliure.

**Comment by aprocter** [comment]
@rkimballn1 True! Just pointing out that parallel builds do work if you have the RAM for it.
