### ISSUE TITLE
Add flag to nbench to ensure synthetic tensor data is always positive

### ISSUE THREAD

**Issue by csullivan** [NervanaSystems/ngraph#1726]
Some ops take input tensors which require their content to be all positive (e.g. the variance tensor in BatchNorm). This information isn't queryable by nbench on a per-op basis, and so I would suggest a flag be added to nbench that causes only positive synthetic data to be generated. Possible alternatives would be to add a min/max command line param. in nbench to specify the RNG domain.

**Comment by rkimballn1** [comment]
What bad would happen if we just made all of the data positive all the time. I'm not positive but it should be ok. A flag is easy too. I'm not trying to be negative, just wondering.

**Comment by csullivan** [comment]
Since nbench is meant only for performance testing and not correctness, I would say this is also likely a valid approach.
