### ISSUE TITLE
Support for ONNX LSTM in nGraph core.

### ISSUE THREAD

**Issue by arogowie-intel** [NervanaSystems/ngraph#1730]
Hi, 

Could you add support for [ONNX LSTM](https://github.com/onnx/onnx/blob/master/docs/Operators.md#LSTM) operator to nGraph core?

**Comment by WilliamTambellini** [comment]
+1 for the LSTM Op.

**Comment by postrational** [comment]
Basic support for the ONNX LSTM was op was added in https://github.com/NervanaSystems/ngraph/pull/1945
