### ISSUE TITLE
Support for ONNX RNN in nGraph core.

### ISSUE THREAD

**Issue by arogowie-intel** [NervanaSystems/ngraph#1732]
Hi,

Could you add support for [ONNX RNN](https://github.com/onnx/onnx/blob/master/docs/Operators.md#RNN) operator in nGraph core?

**Comment by diyessi** [comment]
Since each framework does RNNs in its own way, the ONNX importer should be building the RNN from the more primitive operations that are already available. Examples can be found in the other bridges.
