### ISSUE TITLE
NVGPU: support pad value for padding

### ISSUE THREAD

**Issue by fengleitian** [NervanaSystems/ngraph#1752]

**Comment by csullivan** [comment]
Partially supported in #1759. 

We still need a way to express datatype independent padding with type-based min/max pad value - e.g. using gpu::TypeInfo. We could do this by adding an entry for the ops that require custom padding (e.g. cudnn MaxPool) in GPULayout. The entry would add in an op::Pad and an op::Constant = TypeInfo::Get(element_type)->lowest(). Alternatively, a custom kernel can be used as was done previously in the old static `CUDAEmitter::build_pad`.
