### ISSUE TITLE
Any sample code to benchmark the nGraph GPU performance?

### ISSUE THREAD

**Issue by xiezhq-hermann** [NervanaSystems/ngraph#1815]
I build the nGraph library and try to bridge it to tensorflow in various way, but I found that:
- No GPU backend avaiable for the Python Interface (even no dynamic library to link), where I tried import an ONNX model, it seems the ONNX interface is not very complete.
- I can't compile the Tensorflow (source code) with nGraph support, which turns out this error message: `C++ compilation of rule '@ngraph_tf//:ngraph_tf' failed (Exit 1)`, I tried various version branch but all failed.
- Is any sample code to directly compose the nGraph IR in C++? Especially for GPU backend, it seems something subtle to enable the GPU, since it's even not documented how to config the CUDA env but only some clues in the docker file. And could you please offer a template to compile and run a c++ example, the abc.cpp is not sufficient either.
- No public benchmark, this [post](https://ai.intel.com/high-performance-tensorflow-on-intel-xeon-using-ngraph/) said the GPU support is coming soon, and the document suggest the GPU is now avaiable. Could you please tell me what's the situation now, if so, how shall I take a try?
Thank you very much!

**Comment by diyessi** [comment]
NVIDIA GPU is not supported at this time.
Please see https://github.com/NervanaSystems/ngraph-tf for TensorFlow.

**Comment by xiezhq-hermann** [comment]
Thanks for your reply! When will it be supposed to release?

**Comment by csullivan** [comment]
Hi @xiezhq-hermann, thanks for your interest! We are in active development of the NVIDIA GPU backend and integration testing in TensorFlow is occurring presently. I'm happy to ping this issue when the ngraph-tf GPU integration has been upstreamed.

Cheers.

**Comment by schernolyas** [comment]
Hi!

> NVIDIA GPU is not supported at this time.
> Please see https://github.com/NervanaSystems/ngraph-tf for TensorFlow.

Could anybody update the subject?   Can we use nGrapth with any GUP ? Thanks!

**Comment by diyessi** [comment]
ngraph is part of OpenVINO now: https://github.com/openvinotoolkit/openvino
