### ISSUE TITLE
nGraph fails to build with Ubuntu 18.04 (gcc 7.3.0)

### ISSUE THREAD

**Issue by rl-springer** [NervanaSystems/ngraph#1999]
Building on Ubuntu 18.04 (gcc 7.3.0) fails on master, due to a missing include. Apparently it was pulled in by something else in older versions of gcc but no longer. Patch is below (after which the build worked).

diff --git a/src/ngraph/runtime/cpu/cpu_runtime_context.hpp b/src/ngraph/runtime/cpu/cpu_runtime_context.hpp
index 935301f2..2687a990 100644
--- a/src/ngraph/runtime/cpu/cpu_runtime_context.hpp
+++ b/src/ngraph/runtime/cpu/cpu_runtime_context.hpp
@@ -19,6 +19,7 @@
 #include <chrono>
 #include <cstdint>
 #include <set>
+#include <functional>

 #define TBB_PREVIEW_GLOBAL_CONTROL 1
 #define TBB_PREVIEW_FLOW_GRAPH_TRACE 1

**Comment by diyessi** [comment]
#1992 will fix this. It's next to be merged.
