### ISSUE TITLE
tensorflow : gradient_checker_test failure

### ISSUE THREAD

**Issue by csullivan** [NervanaSystems/ngraph#2003]
[gradient_checker_test.zip](https://github.com/NervanaSystems/ngraph/files/2554750/gradient_checker_test.zip)

**Comment by AyanmoI** [comment]
From initial investigation, lack of double support for dot is causing failures is json 119. An issue has been created for adding support 
https://github.com/NervanaSystems/ngraph/issues/2048
This issue will be reponed when support is added.
