### ISSUE TITLE
环境部署问题

### ISSUE THREAD

**Issue by MichaelJRY** [NervanaSystems/ngraph#2061]
环境部署：
http://ngraph.nervanasys.com/docs/latest/buildlb.html
/******************************/
$ cd /opt/libraries
$ git clone https://github.com/NervanaSystems/ngraph.git
$ cd ngraph && mkdir build && cd build
$ ~/cmake/bin/cmake .. -DCMAKE_INSTALL_PREFIX=~/ngraph_dist -DNGRAPH_ONNX_IMPORT_ENABLE=ON
$ make && sudo make install
/******************************/
make && make install的时候需要download
-- downloading...
     src='https://github.com/intel/mkl-dnn/releases/download/v0.16/mklml_lnx_2019.0.20180710.tgz'
     dst='/opt/libraries/ngraph/build/mkl/src/mklml_lnx_2019.0.20180710.tgz'
     timeout='none'
CMake Error at ext_mkl-stamp/download-ext_mkl.cmake:27 (message):
  error: downloading
  'https://github.com/intel/mkl-dnn/releases/download/v0.16/mklml_lnx_2019.0.20180710.tgz'
  failed

    status_code: 1
    status_string: "Unsupported protocol"
    log: Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

make[2]: *** [mkl/src/ext_mkl-stamp/ext_mkl-download] 错误 1
make[1]: *** [CMakeFiles/ext_mkl.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by diyessi** [comment]
You need to install a libcurl that supports https.

**Comment by diyessi** [comment]
Do `brew install openssl`
https://solitum.net/openssl-os-x-el-capitan-and-brew/

**Comment by rkimballn1** [comment]
If this is on centos then this is from my notes:
```
download cmake source
sudo yum install libcurl-devel
./bootstrap --system-curl
```
I think you have to run make after that. The problem is that the cmake that centos installs does not include ssl support.
