### ISSUE TITLE
CMake: libllvm doesn't force to build its dependency 'ext_llvm' with Ninja

### ISSUE THREAD

**Issue by samolisov** [NervanaSystems/ngraph#2141]
I see the following structure of the dependencies in the `cmake/external_llvm.cmake` file:

```cmake
ExternalProject_Add(
    ext_llvm
    DEPENDS ext_clang ext_openmp
    GIT_REPOSITORY https://github.com/llvm-mirror/llvm.git
...
)
...
add_library(libllvm INTERFACE)
add_dependencies(libllvm ext_llvm)
target_include_directories(libllvm SYSTEM INTERFACE ${EXTERNAL_PROJECTS_ROOT}/llvm/include)
target_link_libraries(libllvm INTERFACE ${LLVM_LINK_LIBS})
```

... then `codegen` depends on `libllvm`:

```cmake
add_library(codegen SHARED ${SRC})
...
target_link_libraries(codegen PRIVATE libllvm ngraph)    
```

CMake works well and generated the ninja-related files but when I'm trying to build `ngraph` using `cmake --build .` the following error occurs:

```
ninja: error: 'ext_llvm-prefix/src/ext_llvm/lib/libclangTooling.a', needed by 'src/ngraph/codegen/libcodegen.so', missing and no known rule to make it
```

Exactly, I can build llvm just specifying the `ext_llvm` target manually:

```
cmake --build . --target ext_llvm

-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
```

but the next dependency is missing:

```
$ cmake --build .
ninja: error: 'mkldnn/lib/libmkldnn.so', needed by 'src/ngraph/libcpu_backend.so', missing and no known rule to make it
```

It looks like I **must** build each external dependency manually using `--target <DEPENDENCY>` command, it's not conveniently.

I do not sure the problem is exactly in ngraph's build files, may be there is a bug in `CMake` and/or `Ninja`, I believe you can help me with this stuff, at least the travis build works fine.

My environment:
- OS: SUSE Tumbleweed
- CMake: 3.13.0 supported by Kitware
- Ninja: 1.8.2

CMake variables:
```
-- NGRAPH_VERSION 0.10.0-rc.1+2579549
-- NGRAPH_VERSION_SHORT 0.10.0
-- NGRAPH_API_VERSION 0.10
-- NGRAPH_UNIT_TEST_ENABLE:      ON
-- NGRAPH_TOOLS_ENABLE:          ON
-- NGRAPH_CPU_ENABLE:            ON
-- NGRAPH_INTELGPU_ENABLE:       OFF
-- NGRAPH_GPU_ENABLE:            OFF
-- NGRAPH_INTERPRETER_ENABLE:    ON
-- NGRAPH_HYBRID_ENABLE:         OFF
-- NGRAPH_NOP_ENABLE:            ON
-- NGRAPH_DISTRIBUTED_ENABLE:    OFF
-- NGRAPH_DEBUG_ENABLE:          OFF
-- NGRAPH_ONNX_IMPORT_ENABLE:    OFF
-- NGRAPH_DEX_ONLY:              OFF
-- NGRAPH_CODE_COVERAGE_ENABLE:  OFF
-- NGRAPH_LIB_VERSIONING_ENABLE: OFF
-- NGRAPH_PYTHON_BUILD_ENABLE:   ON
```

P.S. I've double checked, the problem occurs when Ninja is taken into account, if I tell CMake to generate Unix Makefiles, the dependencies are resolved well.

**Comment by rkimballn1** [comment]
We don't do any testing ninja. It should work if you use make instead of ninja. I can look into this issue but I have never used ninja.

**Comment by rkimballn1** [comment]
We don't support ninja builds
