### ISSUE TITLE
missing <stdexcept> in avg_pool.hpp

### ISSUE THREAD

**Issue by codewdy** [NervanaSystems/ngraph#2260]
avg_pool.hpp(src/ngraph/runtime/reference/avg_pool.hpp) using std::runtime_error, which defined in < stdexcept >.
We should include this header for some compiler.
I got some compile error in gcc 4.9.2.
https://en.cppreference.com/w/cpp/error/runtime_error

**Comment by aprocter** [comment]
Should be fixed by #2263.
