### ISSUE TITLE
Copying a Function

### ISSUE THREAD

**Issue by atraastrum** [NervanaSystems/ngraph#2379]
I import and ONNX model with `import_onnx_model` and get shared pointer to Function. I want to copy the Function. How can I do it? The copy constructor and assignment are deleted and set as private in Function declaration.

**Comment by mbrookhart** [comment]
Hi @atraastrum! Thanks for the question. There’s a utility to clone functions defined here: https://github.com/NervanaSystems/ngraph/blob/af85d85d8fbbb2f906e4cc39f8b6f06fbf7225e3/src/ngraph/graph_util.hpp#L285, it should be available in the `ngraph` namespace, i.e.

```
auto function = onnx_import::import_onnx_model(...);
auto function2 = ngraph::clone_function(*function);
```

Will that suite your needs?

**Comment by atraastrum** [comment]
Thanks @mbrookhart . It is perfect, just what I need.
