### ISSUE TITLE
add standalone flags for each of the distributed libraries used

### ISSUE THREAD

**Issue by aslepko** [NervanaSystems/ngraph#2380]
We're still not doing this? I agree, would make flow much better. On validation side I set it up as originally requested. But that's not very easy to understand unless you have prior knowledge of the flow. Having *MPI* and *MLSL* flags instead would make it much easier to read and maintain.
...
Two independent flags, `NGRAPH_DISTRIBUTED_MPI_ENABLE` and `NGRAPH_DISTRIBUTED_MLSL_ENABLE` will flow better and will be easier to maintain (both for validation and dev). Also, you are removing `NGRAPH_DISTRIBUTED` from several places. I'd recommend using a separate definition for each library.

_Originally posted by @sfvaroglu in https://github.com/NervanaSystems/ngraph/pull/2353#issuecomment-456534364_

**Comment by sasadep** [comment]
addressed the following issue on the PR #2353
