### ISSUE TITLE
support the Gather onnx op

### ISSUE THREAD

**Issue by WilliamTambellini** [NervanaSystems/ngraph#2387]
As today, when trying to import an onnx file embedding a Gather op, ngraph throws : 
Failure
C++ exception with description "Assertion 'unknown_operator_types.empty()' failed at repos/ngraph/src/ngraph/frontend/onnx_import/core/graph.cpp:82:
unknown operations: Gather" thrown in the test body.

the Gather op seems to be available since version 1:  
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Gather

kind

**Comment by postrational** [comment]
Unfortunately, we cannot support the `Gather` operation in nGraph. We're working on adding support for it.

**Comment by diyessi** [comment]
It would be good to give a more descriptive error message when an op is not supported.

**Comment by postrational** [comment]
Support for ONNX `Gather` op was recently added. Please try it now.
https://github.com/NervanaSystems/ngraph/pull/2772
