### ISSUE TITLE
CPU Executable not releasing memory when destroyed

### ISSUE THREAD

**Issue by hildebrandmw** [NervanaSystems/ngraph#2646]
Hi all,

I've noticed an issue with memory resources not being freed when calling `remove_compiled_function` on the CPU Backend. I do not have a great MWE for this, but the issue comes from `runtime::cpu::CPU_CallFrame::cleanup_runtime_context()` never being called.

I've managed to fix it for my purposes by putting `cleanup_runtime_context()` back in the destructor for `CPU_CallFrame` and will open a pull request shortly with that fix.

Mark

**Comment by jbobba** [comment]
Thanks @hildebrandmw It was an accidental deletion.
Your PR has been merged.
