### ISSUE TITLE
Overwrite existing operator warnings

### ISSUE THREAD

**Issue by jnorwood** [NervanaSystems/ngraph#2907]
Why do the `Overwriting existing operator` warnings appear in the test logs?
These occur in three tests that you can see in the current travis-ci log.
[https://travis-ci.org/NervanaSystems/ngraph/jobs/530848958](url)

Is there some way to disable or expect these warnings for the tests?

`[ RUN      ] onnx_INTERPRETER.model_override_op
[WARN] 2019-05-10T17:57:11z src/ngraph/frontend/onnx_import/ops_bridge.cpp 160	Overwriting existing operator: ai.onnx.FalseAdd:1
[       OK ] onnx_INTERPRETER.model_override_op (1 ms)
[ RUN      ] onnx_INTERPRETER.import_non_existing_file
[       OK ] onnx_INTERPRETER.import_non_existing_file (0 ms)
[ RUN      ] onnx_INTERPRETER.model_unsupported_op
[       OK ] onnx_INTERPRETER.model_unsupported_op (0 ms)
[ RUN      ] onnx_INTERPRETER.model_custom_op
[       OK ] onnx_INTERPRETER.model_custom_op (1 ms)
[ RUN      ] onnx_INTERPRETER.model_custom_op_default_domain
[WARN] 2019-05-10T17:57:11z src/ngraph/frontend/onnx_import/ops_bridge.cpp 160	Overwriting existing operator: com.intel.ai.AddQ:1
[       OK ] onnx_INTERPRETER.model_custom_op_default_domain (1 ms)
[ RUN      ] onnx_INTERPRETER.is_op_supported
[WARN] 2019-05-10T17:57:11z src/ngraph/frontend/onnx_import/ops_bridge.cpp 160	Overwriting existing operator: com.intel.ai.AddQ:1
[       OK ] onnx_INTERPRETER.is_op_supported (0 ms)
`

**Comment by jnorwood** [comment]
I see a solution for a similar issue, disabling compiler warnings  with target_compile_options in the cmake file.   `  https://github.com/heinrich5991/ddnet/commit/00154bd28030c323ec1e9f14030a1537909ab267 ` .

Using ctests, I can use set_tests_properties  as shown at ` https://stackoverflow.com/questions/38155543/setting-ctest-cmake-environment-variables-configuration-specific `

their example:

`
if(WIN32)
    set_tests_properties(${my_test} PROPERTIES ENVIRONMENT "MYVAR=\\dir_for_plugins\\$<CONFIG>")
endif()
`

I suppose, though, that the gtests are custom targets, so maybe passing some environment variable for the gtest custom target, as done in the example below from ` https://stackoverflow.com/questions/35029277/how-to-modify-environment-variables-passed-to-custom-cmake-target/35032051 `

`  add_custom_target(newtarget ${CMAKE_COMMAND} -E env NAME=VALUE somecommand) `

**Comment by postrational** [comment]
These warnings occur in tests, which are supposed to verify the behaviour of `Overwriting existing operators`. These warnings are expected and we aren't planning on disabling them at this time.
