### ISSUE TITLE
Support for ConstantOfShape Op

### ISSUE THREAD

**Issue by peterjc123** [NervanaSystems/ngraph#3234]
I get the following error when loading a ONNX model:

`nGraph does not support the following ONNX operations: "ConstantOfShape". `

Since there is support for the Constant Op, I think it won't be hard to support this one.

**Comment by diyessi** [comment]
The problem is that many kernels need shapes known during compilation so they can optimize layout and alignment. We are working on a range of shape variation from those that can be easily computed during compilation to those where the shape is computed during processing.
