### ISSUE TITLE
Did plans change ? 

### ISSUE THREAD

**Issue by Degerz** [NervanaSystems/ngraph#3668]
Previous picture: 

![image](https://user-images.githubusercontent.com/37891629/65570273-9acb1180-df2e-11e9-93c5-47f37b2cc3ee.png)

Updated picture: 

![image](https://user-images.githubusercontent.com/37891629/65570068-e7fab380-df2d-11e9-893a-fc27606d96a8.png)

I see that your team has dropped the idea of supporting PyTorch but I don't see Intel GPUs as being a direct backend for ngraph anymore so does this mean your team has also stopped targeting OpenCL 2.1 as well ?

**Comment by adstraw** [comment]
We have not dropped the idea of supporting PyTorch.  Our initial implementation (through ONNXIFI) is no longer viable.  We hope to find another path.

nGraph has dropped direct support for Intel GPU (via clDNN) but still connects to Intel GPU via PlaidML which lowers through OpenCL

**Comment by Degerz** [comment]
Is your team considering making a SYCL backend for PyTorch instead ? AMD has a HIP backend WIP for PyTorch and Nvidia's CUDA backend is already the gold standard for PyTorch. 

What was the reason for dropping clDNN ? Do you guys also plan on having XLA supported on Tensorflow via nGraph or by some other means ?
