### ISSUE TITLE
RuntimeError: Unable to find any PlaidML devices

### ISSUE THREAD

**Issue by YuriyPryyma** [NervanaSystems/ngraph#3783]
Could someone help me?
I'm following tutorial 
https://www.ngraph.ai/tutorials/onnx-tutorial
Everything works great, but when I set
`runtime = ng.runtime(backend_name='PlaidML')`
I got error "RuntimeError: Unable to find any PlaidML devices"
that`s interesting because when following instructions on plaidml github
https://github.com/plaidml/plaidml
plaidml-setup
is able to see this devices 

>   Default Config Devices:
>      No devices.
> 
>   Experimental Config Devices:
>      llvm_cpu.0 : CPU (LLVM)
>      opencl_intel_gen9_hd_graphics_neo.0 : Intel(R) Corporation Intel(R) Gen9 HD Graphics NEO 
>   (OpenCL)

Do you know the reason why there are no devices?

**Comment by dgkutnic** [comment]
Can you try you can setting the following environment variables to select the proper configurations for your device? This is the command-line equivalent to running plaidml-setup and selecting these settings when prompted.

PLAIDML_EXPERIMENTAL - int (0 or 1) which determines whether to enable experimental mode in PlaidML
PLAIDML_DEVICE_IDS - string which contains the name of the device to use with PlaidML (to see a list of devices, run plaidml-setup)

In your case, it would look somewhat like this:

export PLAIDML_EXPERIMENTAL=1
export PLAIDML_DEVICE_IDS=opencl_intel_gen9_hd_graphics_neo.0

Let me know if this works.

**Comment by YuriyPryyma** [comment]
@dgkutnic yes it worked! Thank you!
I was expecting something like this reading.
It looked like there was no default device.
But I would add this to documentation. It's not obvious

**Comment by dgkutnic** [comment]
Thanks for verifying @YuriyPryyma!

It's in the PlaidML documentation [here](https://github.com/plaidml/plaidml/blob/master/docs/integrating_into_ci.md), but I don't see it mentioned in the ONNX tutorial you linked. @indie can we add this to nGraph's documentation as well?
