### ISSUE TITLE
issue about building ngraph from source

### ISSUE THREAD

**Issue by caofang2008** [NervanaSystems/ngraph#3888]
I tried to build nGraph from source following this instructions http://ngraph.nervanasys.com/docs/latest/buildlb.html#

Howere,The compilation process was always stuck in the following place:
```
$ make python_wheel
……
[ 43%] Built target ext_mkl
[ 44%] Built target ext_mkldnn
[ 44%] Performing download step (git clone) for 'ext_eigen'
cloning into 'ext_eigen'...
```
So I can not build ngraph successfully. 
In addition， I have installed gcc4.8.5，cmake3.9.0, virtualenv16.0.0 in advance.
Does any one know why?

**Comment by diyessi** [comment]
If you are getting stuck cloning eigen it is probably some sort of firewall issue.
