### ISSUE TITLE
How can I avoid building so many 3rdparty libraries but using system/manually installed packages?

### ISSUE THREAD

**Issue by jiapei100** [NervanaSystems/ngraph#4128]
How can I avoid building so many 3rdparty libraries but using system/manually installed packages?
Is there any option for me to select from **cmake** ?

Cheers

**Comment by diyessi** [comment]
`NGRAPH_USE_PREBUILT_LLVM` will use a pre-built LLVM.
Some of those 3rd-party libraries don't maintain back-compatibility and aren't necessarily the same from one distribution to another, which is one reason they are built.
