### ISSUE TITLE
cmake error "NORMALIZE_BOOL"

### ISSUE THREAD

**Issue by CColten** [NervanaSystems/ngraph#4293]
ngraph/src/ngraph/frontend/CMakeLists.txt:22 (NORMALIZE_BOOL)
    Unknown CMake command "NORMALIZE_BOOL"

I build in windows, dldt-R3,  the error occurred !   how to solve , thanks!

how to solve this ? 

when I turn the ngraph build off, it worked.   
I change the thirdparty/CMakeLists.txt  line 52 :    #   include(ngraph.cmake)

**Comment by silee2** [comment]
#4295 should fix this issue.
