### ISSUE TITLE
GPU backend not found

### ISSUE THREAD

**Issue by jinz2014** [NervanaSystems/ngraph#4302]
Use pre-built packages
The easiest way to install ngraph and ngraph-onnx is to use pre-built packages from PyPI. Pre-built packages include the CPU backend and Intel GPU backend.   

However, I didn't find the backend after installing the prebuilt packages based on the following result. Thanks for your instruction.

libcpu_backend.so          libiomp5.so   libmklml_intel.so  libngraph_test_util.a  libonnxifi-ngraph.so   libtbb.so    python2.7
libinterpreter_backend.so  libmkldnn.so  libngraph.so       libnop_backend.so      libplaidml_backend.so  libtbb.so.2  python3.6

Could you please update the installation guide ?

In addition, I got the following error when using the plaidml backend for the example in the guide:

RuntimeError: The PlaidML backend doesn't currently implement the 'ConvertLayout' operation

Thanks

**Comment by gkorepanov** [comment]
Same here, I have both problems:
1. No GPU backend available in prebuilt wheels
2. `RuntimeError: The PlaidML backend doesn't currently implement the 'ConvertLayout' operation` when trying to run inference with `PlaidML` backend.
