### ISSUE TITLE
[ ERROR ] Check 'axis < static_cast<size_t>(input_rank)' failed 

### ISSUE THREAD

**Issue by Z-Xiong** [NervanaSystems/ngraph#4342]
When I run the OpenVINO sample by Raspberry Pi with NCS 2:
`./armv7l/Release/object_detection_sample_ssd -m face-detection-adas-0001.xml -d MYRIAD -i /home/pi/Pictures/1.jpg `
then:
```
 Check 'axis < static_cast<size_t>(input_rank)' failed at /teamcity/work/scoring_engine_build/releases_2020_1/ngraph/src/ngraph/op/gather.cpp:140:
While validating node 'Gather[Gather_852](patternLabel_848: float{10,20,30}, patternLabel_849: int64_t{5}, patternLabel_851: int64_t{1}) -> (??)':
The axis must => 0 and <= input_rank (axis: 4294967295).
```
Who can tell me how to solve it?

**Comment by r4ghu** [comment]
I am also facing the similar issue. I tried both C++ and Python samples.

I am using Raspberry Pi 4B with Intel NCS 2. OpenVINO version 4.2.0.

**Comment by dzwpusa** [comment]
I am also facing the similar issue. I am also using Raspberry Pi 4B with Intel NCS 2. OpenVINO version 4.2.0.

**Comment by diyessi** [comment]
We fixed another one of these. I think we need to remove the `static_cast<size_t>` operator and go through and change all the callers to the method that returns an `int64_t`.

**Comment by tgonzalez89** [comment]
I'm also having the same issue using OpenVINO v2020.1

**Comment by diyessi** [comment]
https://github.com/NervanaSystems/ngraph/pull/4417 is intended to address the issue.
