### ISSUE TITLE
How to specify SYSTEM 3rd-party libraries?

### ISSUE THREAD

**Issue by jiapei100** [NervanaSystems/ngraph#4511]
It looks ngraph will **automatically** install/build its own 
- protobuf
- mkldnn
- tbb
- gtest
- llvm
- eigen
- json
etc.

How about if I had **ALL** the above 3rd-party libraries installed from repository or manually **ALREADY** on my customized system?

To build ngraph is a kind of complicated and it seems it **always** download the above packages onto out-of-source directories.

Any suggestions?

Cheers
Pei

**Comment by diyessi** [comment]
We do this because a lot of 3rd-party libraries aren't good about maintaining forward/backward compatibility, and not all distributions package them without making "improvements".

**Comment by jiapei100** [comment]
@diyessi 
Thank you for your prompt reply. In that case, you'll meet a lot of problems like:

```
dpkg: error processing archive ....../ngraph/build_18.04/ngraph_0.29.0-6_amd64.deb (--install):
 trying to overwrite '/usr/local/lib/libdnnl.so', which is also in package dnnl 1.1.0-6
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing
```

That is to say, under Linux, to install **ngraph**, I may have to overwrite some **previously installed packages** (newer or older version) which is probably used by some other packages...


I can understand under Windows, some software has its own folder to contain the dlls that it relies on. That is to say: under Windows, it's OK to have some dlls of different versions. However, under Linux, .so files are stored under some particular folders which may bring the conflicts. It's still OK under Linux to have multiple versions of the same package, but.... Anyway.... 

**ngraph's dnnl is trying to replace my manually installed dnnl but failed.**
