### ISSUE TITLE
How to use nGraph with C API ?

### ISSUE THREAD

**Issue by fujunwei** [NervanaSystems/ngraph#4521]
Namespace | Description | Location in Repo | Docs
-- | -- | -- | --
ngraph | The Intel nGraph C++ API | ngraph | Implicit namespace omitted from most API documentation
builder | Convenience functions that create additional graph nodes to implement commonly-used recipes; for example, auto-broadcast | builder | Coming Soon

Does the table means the API in builder namespace will export all C++ APIs defined in nGraph with C API? Some ops have wrapped such as split/reshape/matmul and so on, how to use Conv op that doesn't need to be quantized?

**Comment by rkimballn1** [comment]
I think it means that the docs for the builder API are coming. I don't know of plans to make a C API for ngraph. Is there a need for such an API?

**Comment by diyessi** [comment]
No plans.
