### ISSUE TITLE
Ops can't take a scalar value as input

### ISSUE THREAD

**Issue by postrational** [NervanaSystems/ngraph#477]
ngraph++ ops currently can only take `Node` objects as arguments. 

When trying to use scalar values as input in Python ngraph++:

```python
input_node = ng.parameter(shape=[2, 2], name='a')
model = (input_node + 1)
```

Produces:

```TypeError: unsupported operand type(s) for +: '_pyngraph.op.Parameter' and 'int'```

How can we address this to get classic-ngraph-like behaviour?

```python
>>> import ngraph as ng
>>> 
>>> axes = ng.make_axes((ng.make_axis(2), 
>>>                      ng.make_axis(2)))
>>> input_node = ng.placeholder(axes=axes)
>>> 
>>> model = (input_node + 1)
>>> 
>>> transformer = ng.transformers.make_transformer()
>>> computation = transformer.computation(model, input_node)
>>> 
>>> computation(np.array([[5, 5], [5, 5]]))
array([[ 6.,  6.],
       [ 6.,  6.]], dtype=float32)
```

**Comment by diyessi** [comment]
To make Python have this behavior, you need to add something like the `as_node` that was in Python. We leave the definition and implementation of DWIM behavior to the bridges since "what I mean" isn't the same for all frameworks.

**Comment by postrational** [comment]
We already have some solutions like this in our Python API layer.
