### ISSUE TITLE
openvino error

### ISSUE THREAD

**Issue by natxopedreira** [NervanaSystems/ngraph#4794]
Hello

Im not sure if this is the correct place to put this but i just compiled openvino from source trying to solve an persistent issue on last raspbian versions.

But im getting the same error again.

Is pointing to ngraph/op/reshape.cpp:100 so thats why im posting here

**Using openCv**

cv2.error: OpenCV(4.3.0-openvino) ../opencv/modules/dnn/src/ie_ngraph.cpp:600: error: (-2:Unspecified error) in function 'initPlugin'

`> Failed to initialize Inference Engine backend (device = MYRIAD): Check 'input_shape_product.get_length() == shape_size(m_output_shape)' failed at /home/pi/openvino/ngraph/src/ngraph/op/reshape.cpp:100:`

`
While validating node 'v0::Reshape Reshape_18831(PriorBoxClustered_18234[0]:f32{2,2760708352}) -> (dynamic?)':
Product of output shape dimensions does not match product of argument shape dimensions (output shape: Shape{1, 2, 2760708352}, argument shape: {2,2760708352})
`

**Using native engine**

`import cv2`
`from openvino.inference_engine import IECore, IENetwork`
`ie = IECore()`
`net = ie.read_network('face-detection-0100.xml', 'face-detection-0100.bin')`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "ie_api.pyx", line 136, in openvino.inference_engine.ie_api.IECore.read_network`
`  File "ie_api.pyx", line 157, in openvino.inference_engine.ie_api.IECore.read_network`
`RuntimeError: Check 'input_shape_product.get_length() == shape_size(m_output_shape)' failed at /home/pi/openvino/ngraph/src/ngraph/op/reshape.cpp:100:`
`While validating node 'v0::Reshape`
`Reshape_1991(PriorBoxClustered_1394[0]:f32{2,3443079936}) -> (dynamic?):`
`Product of output shape dimensions does not match product of argument shape dimensions`
`(output shape: Shape{1, 2, 3443079936}, argument shape: {2,3443079936}).`

**Comment by diyessi** [comment]
The problem is from the input to PriorBoxClustered; 2x2760708352 doesn't look like the shape you would expect as an input.

**Comment by natxopedreira** [comment]
Thank you, so you say that is not from your library, is from the wrong format that the input layer receives no, so the problem is in the openvino path, correct?

**Comment by diyessi** [comment]
Not exactly; something went wrong with the size of the input to PriorBoxClustered, probably a bad signed/unsigned conversion. Wherever that big number came from is the op with the problem. If there's a `PriorBox` in that area, @4745 might be the fix and it might not be in the OpenVINO sources you are using yet.

**Comment by natxopedreira** [comment]
Ah ok, i understand and thanks for your reply!!

You know if there is a patch i can apply ?

**Comment by diyessi** [comment]
I should have said #4745 . It's a pretty simple change.

**Comment by natxopedreira** [comment]
Thank you so much!! i will try to apply that patch and compile again

I see today openvino repo was updated and i see they removed ngraph module.... i have to take a look

**Comment by natxopedreira** [comment]
Sorry to disturb again, the branch that was linked in openvino was the master branch, in that branch the files mentioned in that pull request are in a different location, they are under a folder named "experimental". Will work if i apply those patches in that location or i will need to use your dynamic branch instead master?

Thanks again

**Comment by diyessi** [comment]
It should work; it's just making the computation signed so that negative numbers don't turn into large positive numbers

**Comment by natxopedreira** [comment]
sadly it doesn't work, keep trowing same error

**Comment by diyessi** [comment]
Do you know the shape of the PriorBox input and the attributes it of the PriorBox op?

**Comment by natxopedreira** [comment]
No, sorry

But if you tell me how to get that info i will do it

**Comment by natxopedreira** [comment]
If helps error seems related to only raspberry enviroment and "caused by the new IR v10 format.."

**Comment by diyessi** [comment]
Are you starting with an OpenVINO graph? I think the PriorBox attributes (min_size, aspect_ratio, flip, clip, step, offset, variance, scale_all_sizes, fixed_ratio, fixed_size, density) would be almost the same in that graph, as would the inputs to the PriorBox (output_size and image_size tensors).

**Comment by natxopedreira** [comment]
You mean to use the workbench to visualize a graph of the model? Sadly you can not do that on raspberry, as the raspbian package do not have those tools....

I can do that in a ubuntu machine if helps....

[https://docs.openvinotoolkit.org/latest/_docs_Workbench_DG_Visualize_Model.html](https://docs.openvinotoolkit.org/latest/_docs_Workbench_DG_Visualize_Model.html)

**Comment by diyessi** [comment]
I checked with some OpenVINO people, and they ask that you move the conversation over there since there are multiple places things could be going wrong (and any fixes will be in the ngraph in the OpenVINO repo).

**Comment by natxopedreira** [comment]
Thank you, i appreciate your help!!
