### ISSUE TITLE
Pybind11 error when building nGraph wheel

### ISSUE THREAD

**Issue by robinvanemden** [NervanaSystems/ngraph#4864]
On building nGraph wheel as described in "[Build the nGraph wheel](https://www.ngraph.ai/tutorials/onnx-tutorial#id8)", the following error is thrown:

```
...
/root/ngraph/python/src/pyngraph/node_factory.cpp:125:43: error: no matching function for call to ‘pybind11::dict::contains(const string&) const’
             if (m_attributes.contains(name))
...
```

But when switching from `pybind11` _head_ to _release v2.4.3_, the wheel builds correctly. So it appears some breaking changes have been introduced in the latest `pybind11` version.

**Comment by diyessi** [comment]
The ngraph python binding developers are now working with the version of nGraph included with OpenVINO.

**Comment by robinvanemden** [comment]
Thanks for the heads up!
