### ISSUE TITLE
Feature request: GCPU code generation.

### ISSUE THREAD

**Issue by robinvanemden** [NervanaSystems/ngraph#4865]
Would it be possible to implement code generation into the GCPU backend as well? Such a feature would be very useful to us, as it would enable us to integrate NGraph generated code with both IA processor based devices (through CPU code generation) and existing C / C++ MCU applications, edge devices, etc.

**Comment by diyessi** [comment]
ngraph has been moved into OpenVINO: https://github.com/openvinotoolkit/openvino
