### ISSUE TITLE
Integrating ngraph into Godot Engine

### ISSUE THREAD

**Issue by fire** [NervanaSystems/ngraph#4886]
Hi NervanaSystems,

I was wondering would it be a good approach to integrate ngraph into a non-official module for Godot Engine.

My concept is that I would take the ngraph compiler and plaidml. Then, convert the build system to scons and delete the TBB dependency.

It's fairly hard to get a complete list of dependencies.

I assume that plaidml uses opencl 1.2. I would prefer vulkan compute but that is a lot of work. Having vulkan compute is what one of your competitors at https://github.com/Tencent/ncnn did.

My models will be defined in onnx and then converted to be ngraph compatible.

Godot Engine is a c++ engine.

Two obvious projects to create a demo for would be a many to [single] voice style transfer and image superscaling. That would be https://github.com/hujinsen/StarGAN-Voice-Conversion and waifu2x https://github.com/nihui/waifu2x-ncnn-vulkan.

[Side note] I did try converting to https://github.com/godot-extended-libraries/godot-tensorflow-workspace but it had no official gpu support on desktops. See https://github.com/tensorflow/tensorflow/issues/28830

[Multithreading] Godot Engine has a ban on OPENMP because that feature add a msvc redistributable. TBB would be also be ran in unsupported single executable mode, which is not recommended. https://github.com/oneapi-src/oneTBB/blob/tbb_2020/build/big_iron.inc

**Comment by diyessi** [comment]
PlaidML has switched to starting with an MLIR dialect. I believe they can generate code for TBB, OpenMP, and possibly neither.

**Comment by fire** [comment]
I wonder how usable is https://github.com/llvm/llvm-project/commit/896ee361a641bf9529bb9103a3a018b1c28dc21d
