### ISSUE TITLE
How to implement Depthwise_Convolution via GroupConvolution?

### ISSUE THREAD

**Issue by mingmingtasd** [NervanaSystems/ngraph#4898]
Hi,
I want to implement Depthwise_Convolution now, and I plan to use  GroupConvolution to do it. But I failed when setting the parameters of GroupConvolution. It seems that the dimensions of data_batch and filters are not right. How to set the dimensions and the group number for GroupConvolution?
Thanks!

**Comment by mingmingtasd** [comment]
Resolved, closed.

**Comment by thameemtraining** [comment]
@mingmingtasd 

Can you please describe how you managed to solve this?

I am facing an issue with the v1 op as well?

**Comment by mingmingtasd** [comment]
> @mingmingtasd
> 
> Can you please describe how you managed to solve this?
> 
> I am facing an issue with the v1 op as well?

Hi,
I find that if I set weights dimensions as 
`      SizeVector weights_dims{params.depth_out, 1, 1, params.filter_height,
                              params.filter_width};`, then 
`      conv_node = std::make_shared<op::v1::GroupConvolution>(
          input_node, weights_node,
          Strides(strides), CoordinateDiff(padBegin), CoordinateDiff(padEnd),
          Strides(dilations));`,
I will get correct result.
