### ISSUE TITLE
Missing type name check for distinguishing between bfloat16 and float16 when instantiating element::Type in ngraph deserializer

### ISSUE THREAD

**Issue by AkashIwnK** [NervanaSystems/ngraph#4927]
When deserializing a json file with ngraph that uses input type of float16, I kept getting "incorrect precision" error  with reported element type being bfloat16 in OpenVINO despite the fact that ngraph was not using bfloat16 at all. On inspecting the deserializer code carefully i realized that although the type read from the json file was "float16", which was correct", but the "read_element_type" returns bfloat16 type instead of float16. This is because the "element::Type" constructor checks for type bitwidth, whether it is quanlized and signed type or not, etc., which are the same for bfloat16 and float16, but it does not check for the name of the type which is the only way for the constructor to know whether the intended type for allocation is bfloat16 or float16.

**Comment by diyessi** [comment]
ngraph has been moved into OpenVINO: https://github.com/openvinotoolkit/openvino
