### ISSUE TITLE
Are batch sizes fixed in ngraph?

### ISSUE THREAD

**Issue by guy4261** [NervanaSystems/ngraph#4951]
Hello, is there a way to use ngraph/plaidml with dynamic batch size?
If I `torch.onnx.export` with a dynamic batch size:

```python
torch.onnx.export(..., {"input": {0: "batch_size"}, "output": {0: "batch_size"}})
```

When I try to load it to `ngraph` , I get a `RuntimeError`:

```python
import onnx
from ngraph_onnx.onnx_importer.importer import import_onnx_model
onnx_protobuf = onnx.load("model.onnx")
ng_function = import_onnx_model(onnx_protobuf)
Traceback (most recent call last):
  File "foo.py", line 9, in <module>
    ng_function = import_onnx_model(onnx_protobuf)
  File "/Users/grapaport/ng/lib/python3.6/site-packages/ngraph_onnx/onnx_importer/importer.py", line 36, in import_onnx_model
    return onnx_import.import_onnx_model(onnx_protobuf.SerializeToString())
RuntimeError: Check '(batch_size.is_dynamic() || static_cast<size_t>(batch_size) > 0)' failed at /jenkins/workspace/ngraph-core-mac-wheel-generation/ng/src/ngraph/validation_util.cpp:316:
While validating node 'Convolution[Convolution_523](Parameter_522: float{0,3,224,224}, Constant_4: float{64,3,7,7}) -> (??)':
Batch size is zero.
```

Is this not supported by ngraph? If not - is there a way to bypass this?
EDIT: original PyTorch model can accept any batch size that does not OOM the machine.

**Comment by diyessi** [comment]
ngraph has been moved into OpenVINO: https://github.com/openvinotoolkit/openvino

**Comment by guy4261** [comment]
How come the main page of `ngraph` doesn't mention this?
https://github.com/NervanaSystems/ngraph
I got `ngraph` working in 10 minutes - OpenVINO's Python API isn't nearly as clear :(
Good luck in your new home!

**Comment by diyessi** [comment]
#4952

**Comment by guy4261** [comment]
🙇 
Thanks!!!

**Comment by aoxipo** [comment]
> 🙇 Thanks!!!

hello ， would you like to share the ngroph-core wheel ？i try to install like pip or cmake the wheel ， but failed 。  think you！ plz

**Comment by diyessi** [comment]
Everything migrated into OpenVINO with a somewhat different organization.
