### ISSUE TITLE
op::Dot behaviour similar to numpy.matmul

### ISSUE THREAD

**Issue by arogowie-intel** [NervanaSystems/ngraph#557]
Hi All,

We have to implement `MatMul` operator in `ONNX` according to its [standard](https://github.com/onnx/onnx/blob/master/docs/Operators.md#MatMul) which states that `MatMul` should behave similar to [numpy.matmul](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html).

In order to achieve this we have tried to use `op::Dot`, however currently it seems to be not possible straightforward. Please let us know whether and when would you be able to add such functionality to `op::Dot` operator, since lack of this feature is blocking us from further development.

Let me know describe for you the `numpy.matmul` behavior with some examples:

```
a
>>> array([[[ 0,  1,  2,  3],
            [ 4,  5,  6,  7]],

           [[ 8,  9, 10, 11],
            [12, 13, 14, 15]]])

a.shape
>>> (2, 2, 4)

b
>>> array([[[ 0,  1],
            [ 2,  3],
            [ 4,  5],
            [ 6,  7]],

           [[ 8,  9],
            [10, 11],
            [12, 13],
            [14, 15]]])

b.shape
>>> (2, 4, 2)
```

According to `numpy.matmul` documentation, there are two important statements:
> If either argument is N-D, N > 2, it is treated as a stack of matrices residing in the last two indexes and broadcast accordingly.

and:
> Stacks of matrices are broadcast together as if the matrices were elements.

Thus considering we have tensors `a` and `b` previously defined `numpy.matmul` generates following output:
```
c = np.matmul(a,b)
c
>>> array([[[ 28,  34],
            [ 76,  98]],

           [[428, 466],
            [604, 658]]])

c.shape
>>> (2, 2, 2)
```
Now if we dive into details of how it works we see that, each element is a dot product of specified axes:
```
c[0,1,1]
>>> 98
np.dot(a[0, 1, :], b[0, :, 1])
>>> 98
```
So the last two dimensions are treated as a conventional 2D matrices and multiplied together. This of course enforces that the last two dimensions of each tensor have to have compatible dimensions enabling matrix multiplications.
The remaining dimensions define _stack of matrices_ which tell us, how many times we have to repeat the 2D matrix multiplication.  Now `numpy` enables broadcasting of that remaining dimensions if they are _compatible_. The best description I could found is:

>To determine if two shapes are compatible, Numpy compares their dimensions, starting with the trailing ones and working its way backwards (For the shape (4, 3, 2) the trailing dimension is 2, and working from 2 "backwards" produces: 2, then 3, then 4.). If two dimensions are equal, or if one of them equals 1, the comparison continues. Otherwise, you'll see a ValueError raised (saying something like "operands could not be broadcast together with shapes ...").
>When one of the shapes runs out of dimensions (because it has less dimensions than the other shape), Numpy will use 1 in the comparison process until the other shape's dimensions run out as well.
>Once Numpy determines that two shapes are compatible, the shape of the result is simply the maximum of the two shapes' sizes in each dimension.

Consider following examples:
```
a = np.array(...) # a 3D array
a.shape
>>> (2, 2, 4)
d = np.array(...) # a 4D array
d.shape
>>> (1, 2, 4, 2)
e =  np.matmul(a,d)
e.shape
>>> (1, 2, 2, 2)
```
In above example `numpy` broadcasted `a` matrix along the 1-st dimension of  `d` matrix.
```
k  = np.array(...) # a 4D array
k.shape
>>> (2, 3, 2, 2)
m = np.array(...) # a 4D array
m.shape
>>> (2, 1, 2, 4)

n = np.matmul(k,m)
n.shape
>>> (2, 3, 2, 4)
```

**Comment by postrational** [comment]
Resolved.
