### ISSUE TITLE
Emit CUDA kernels concurrently/prior to LLVM graph emission

### ISSUE THREAD

**Issue by csullivan** [NervanaSystems/ngraph#637]
Currently the gpu_emitter emits code that is compiled at runtime by LLVM. This compiled code then generates CUDA kernels which are compiled at RT and then run. Thus, the compiled graph execution includes runtime compilation of CUDA kernels. 

As far as I can tell, there isn't anything that constrains the functionality to proceed in this way. For performance optimization purposes and benchmarking, I believe it would be better to have the gpu_emitter handle the cuda kernel runtime compilation first, prior to LLVM compilation, so that when the LLVM compiled function is executed, the computations that occur are primarily based on executing the graph and not generating CUDA. 

I have checked with some of the MKLDNN folks and they originally also used our current method but eventually switched to having the MKLDNN generated prior/concurrently to the LLVM compilation. This is achievable by passing a context variable from the generating code to the LLVM compiled function (```m_compiled_function```) which contains pointers and other information that the emitted code can use to make the appropriate CUDA kernel calls. This is how it is currently performed on the CPU transformer side, see for example ```CPURuntimeContext```.

**Comment by jmenon** [comment]
> It's not abandoned for inference.

This raises quite a few questions. It'd be good to discuss how we plan to address this. We also want negligible compilation overhead for inference in addition to execution latency. And the current IA-side codegen definitely does not allow for this "standalone" use-case at any rate. If we end up leveraging external kernels (ex. Halide-based) for most (if not all) performance-sensitive ops, then compiling code on-the-fly adds zero value in addition to not being "standalone".

**Comment by fengleitian** [comment]
There is always some trade off, even for inference. Some might require to start faster, some require to run faster, and other might want some balanced load. All lead to different approach.

**Comment by csullivan** [comment]
Compile time emission of cudnn and ngraph compilation of cuda kernels (prior to clang JIT) is now possible as of PR #837. Please open a new issue for further discussion of standalone binary support.
