### ISSUE TITLE
Summary of the frameworks supported.

### ISSUE THREAD

**Issue by Ajay191191** [NervanaSystems/ngraph#730]
When I see the overview on the github [page](https://github.com/NervanaSystems/ngraph) or the [docs](http://ngraph.nervanasys.com/docs/latest/index.html), I don't get a general idea of what frameworks are currently supported and what are not unless I go to the http://ngraph.nervanasys.com/docs/latest/framework-integration-guides.html page and look at them.

I think it would be great to have a summary on the front page like what's supported and what's 
coming in the future. For example:
These frameworks are currently supported: neon, MXNet, TensorFlow. 
Framework support in the pipeline: PyTorch… etc.

**Comment by rkimballn1** [comment]
Might be nice to list the backend support as well.
