### ISSUE TITLE
No Permissions to View Docs

### ISSUE THREAD

**Issue by MedLexAI** [NervanaSystems/ngraph#772]
Looks like all of the doc links from the website such as the install docs have bad permissions. Or at least I am getting a "you don't have permission to view this" error on those links:

http://ngraph.nervanasys.com/docs/latest/install.html
http://ngraph.nervanasys.com/docs/latest

403 forbidden etc.

**Comment by diyessi** [comment]
It is supposed to work, and it works for me now, but that is from my phone, which is partially within Intel's network.

We have been trying to get an automatic doc build push through the firewall working, and you might have hit an issue with it related to some testing issues yesterday.

**Comment by indie** [comment]
The docs are back up; the 403 / 404 errors folks were getting yesterday were related to the new deployment pipeline.  Let us know if you have any further issues @MedLexAI
