### ISSUE TITLE
Python binary wheel - issues with rpath

### ISSUE THREAD

**Issue by postrational** [NervanaSystems/ngraph#809]
There is a problem with the way we are currently building out Python binary wheel files for ngraph.
The ngraph Python wrappers are compiled into `_pyngraph.so`, which is linked dynamically with `libngraph.so` and other library files.

`_pyngraph.so` uses an `rpath` value of `../../` to find `libngraph.so` 2 directory levels up from its own location. This works fine in most cases, because after installation of the Python binary wheel into a virtualenv files are stored in the following way:

```
$ find venv -name *ngraph*
venv/lib/python2.7/site-packages/_pyngraph.so
venv/lib/python2.7/site-packages/ngraph
venv/lib/libngraph.so
```

Unfortunately, if we try to install the same package in the sytem Python of CentOS, we get a different directory layout:
```
/usr/lib64/python2.7/site-packages/_pyngraph.so
/usr/lib64/python2.7/site-packages/ngraph
/usr/lib/libngraph.so
```

#### Steps to reproduce:

1. You can build a Python binary wheel using the attached Dockerfile [Dockerfile.zip](https://github.com/NervanaSystems/ngraph/files/1876117/Dockerfile.zip)

```
$ docker build -t ngraph_dist_centos .
```

2. You can test the wheel in a container using the built Docker image

```
$ docker run ngraph_dist_centos bash
[docker] # cd /root/ngraph/python/dist
[docker] # pip install ngraph-*-cp27-*.whl
[docker] # python
>>> import ngraph
(...)
ImportError: libngraph.so: cannot open shared object file: No such file or directory
```

#### Possible solutions

There are a number of alternative apporaches we can take to solve this issue:

* modify `setup.py` to copy library files into a Python module directory e.g. `ngraph/impl/` change `rpath` value accordingly

* currently `setup.py` stores library files in `data_files`. After installation they get placed in a path relative to `sys.prefix`, which can be different system to system. 
We could set `os.environ['LD_LIBRARY_PATH'] = sys.prefix + 'path/to/libs'` at runtime (specifically during import of `ngraph.impl` module or its submodules).

**Comment by diyessi** [comment]
Some package managers replace the RPATH value during installation.

**Comment by cconvey** [comment]
This might be a good job for [`auditwheel`](https://stackoverflow.com/a/42106034/387887).

I found some other comments in that StackOverflow thread to be helpful  as well.
