### ISSUE TITLE
Compilation failure on CentOS because of cudnn_v7.h

### ISSUE THREAD

**Issue by WilliamTambellini** [NervanaSystems/ngraph#864]
Just a little compilation failure under CentOS 7 : 

In file included from 
~/repos/ngraphwt/src/ngraph/runtime/gpu/gpu_cuda_context_manager.hpp:22:0,
                 from ~/repos/ngraphwt/src/ngraph/runtime/gpu/gpu_runtime_context.hpp:22,
                 from ~/repos/ngraphwt/src/ngraph/runtime/gpu/gpu_call_frame.hpp:27,
                 from ~/repos/ngraphwt/src/ngraph/runtime/gpu/gpu_call_frame.cpp:
~/repos/ngraphwt/src/ngraph/runtime/gpu/gpu_util.hpp:27:22: fatal error: cudnn_v7.h: No such file or directory

This is because under CentOS/RedHat (non debian/ubuntu os), the cudnn packages from nvidia are installing include/cudnn.h, not cudnn_v7.h.
Creating a symlink is of course doing the job but should gpu_util.hpp simply include <cudnn.h> ? 
Cheers

**Comment by diyessi** [comment]
Thanks for the report.

**Comment by csullivan** [comment]
God catch @WilliamTambellini. I've made a small PR regarding your suggested change. Please check that the referenced branch resolves the issue for you.

**Comment by csullivan** [comment]
Closing as PR #879 has been merged and resolves this issue. Feel free to reopen it if you find a similar issue on other systems.
