### ISSUE TITLE
CUDA 9 support

### ISSUE THREAD

**Issue by csullivan** [NervanaSystems/ngraph#947]
Need to test compatibility, update CI docker, and update build scripts. Required for compatibility with clang 3.9. This issue is blocking PR #906.

**Comment by WilliamTambellini** [comment]
Hi @csullivan 
The gpu runtime cmakelist file in ~/repos/ngraph/src/ngraph/runtime/gpu  is still imposing cuda 8 : 
find_package(CUDA 8 REQUIRED)
- Is it on purpose ?
- is cuda 9 support still unofficial ?
Cheers
W.

**Comment by csullivan** [comment]
Hi @WilliamTambellini, it is supported. #906 updates the cmakelist with 
https://github.com/NervanaSystems/ngraph/pull/906/files. It is held up by an internal CI upgrade that is needed for testing. You shouldn't have any issues with CUDA 9 and ngraph.
