### ISSUE TITLE
Convolution groups

### ISSUE THREAD

**Issue by tsocha** [NervanaSystems/ngraph#956]
To achieve full compatibility  with ONNX we need to implement support for alexnet topology and convolution layer but these models require a convolution layer with groups.
Are there any plans to implement groups in convolution layer?

Examples:
Weights shape: `(6, 2, 3, 2)`
Data shape: `(2, 4, 6, 5)`
Groups: 2

Weights shape: `(4, 1, 3, 3)`
Data shape: `(2, 4, 6, 6)`
Groups: 4

**Comment by mbrookhart** [comment]
We do something like this with slices and concats in the MXNet convolution op

**Comment by tsocha** [comment]
It was very helpful, thanks!
