### ISSUE TITLE
Dynamic reshape

### ISSUE THREAD

**Issue by tsocha** [NervanaSystems/ngraph#957]
To achieve full compatibility  with ONNX we need to implement support for reshape with target shape is known in runtime and passed as input parameter.
Are there any plans for enable dynamic reshape?

ONNX specification:
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Reshape

**Comment by indie** [comment]
Does the latest merge to master with the latest Python API documentation help?

**Comment by diyessi** [comment]
If it's on ONNX we need to support it.
